AM_CXXFLAGS = -Wall
AM_CXXFLAGS += -Wextra
AM_CXXFLAGS += -Werror
AM_CXXFLAGS += -I$(top_srcdir)/include

AM_LDFLAGS = $(BOOST_LDFLAGS)

GZC_UTIL_LOGGER_VERSION = 1:1:0
GZC_UTIL_SERIALIZE_VERSION = 1:1:0
